### PR TITLE
High CPU due to socket retry

### PR DESCRIPTION
**Pull request by PedroKantar**

### CODE REVIEW

**Comment by PedroKantar** [comment]
@MatthieuLemoine 

I Have followed your advice and implement a decreasing delay between re-connection attempts.
I tested the code (connected, not connected, connected) and works OK.
I set up the max delay (```RETRY_MAX_TEMPO```) to 15 seconds.

**Comment by MatthieuLemoine** [comment]
Thanks a lot @PedroKantar.

It's great ! I just made some modifications so that we don't have to use a global `retryCount`. Can you review it and test it again ?

**Comment by PedroKantar** [comment]
Hi, modifications look OK to me, I'm testing it..

**Comment by PedroKantar** [comment]
It is OK, I tested the modification and it works.
Thanks!

**Comment by MatthieuLemoine** [comment]
Merged ! Thanks for this PR !

**Comment by PedroKantar** [comment]
👍

**Comment by MatthieuLemoine** [comment]
Release in [v1.1.2](https://github.com/MatthieuLemoine/push-receiver/releases/tag/v1.1.2)

**Pull request merged**
